### PR TITLE
add countries, update file

### PR DESCRIPTION
**Pull request by Trinidad-KianLee**
Good day!

Here are my countries of the world codes and I updated some of my files. I kindly request for your review and suggestions. Thank you!

### CODE REVIEW

**Comment by Martinez-Emmanuel** [comment]
hello, kian. i am currently reviewing your code. i will update you as soon as i identify any changes to be made (if there's any). @Trinidad-KianLee

**Comment by Martinez-Emmanuel** [comment]
Hello, Kian. Most of your codes are commendable and follow our coding guidelines. However, there have been a few oversights in your `script.js` file.
## 1. Change the `var` keyword to `let`:

https://github.com/PUP-BSIT/exercise-14-sixth_sense/blob/7f880c27ab3346571647a87caf5a6d38ed5792bf/trinidad_kianlee/script.js#L61

As per slide 10 in our coding guidelines: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d183194fb_0_0

## 2. Use guard clause here when possible to catch early errors, such as in this case:
https://github.com/PUP-BSIT/exercise-14-sixth_sense/blob/7f880c27ab3346571647a87caf5a6d38ed5792bf/trinidad_kianlee/script.js#L62-L64

For example, you can add a guard clause if user tries to submit an empty value, or if the country does not exist. Here's a simple way of doing so:

```javascript
.then((response) => {
      if (!response.ok) {
        throw new Error('Country not found');
      }
      return response.json();
    })
``` 
This is stated in slide 10 as well: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d183194fb_0_0

## 3. The second `fetch` in your code should **NOT** be nested inside the second `then` method:
https://github.com/PUP-BSIT/exercise-14-sixth_sense/blob/7f880c27ab3346571647a87caf5a6d38ed5792bf/trinidad_kianlee/script.js#L76-L77

## Instead, you can chain them by returning another fetch. Here's a simple example of doing so:

```javascript
    .then((region) => {
      return fetch("https://restcountries.com/v3.1/region/" + region);
    })
    .then((response) => response.json())
    .then((data) => {
      let regionCountries = document.getElementById("region_countries");
      regionCountries.innerHTML = "<h2>Countries in the same region:</h2>";
      data.forEach((country) => {
        regionCountries.innerHTML += `
          <p>${country.name.common}</p>
          <img src="${country.flags.png}" alt="${country.name.common} flag">`;
      });
    })
``` 

### You can add guard clause here to improve the code.

This is also stated in the slide 14 of our coding guidelines: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g2637aafa621_0_10

So far, these are the immediate changes that should be made to strictly adhere to our coding guidelines. I've also noticed that the fetching of countries data is extremely slow and even fails many times, but I think this problem is more on server-side. If you have any questions or concerns, feel free to raise it here right away.

**Review by Martinez-Emmanuel — CHANGES_REQUESTED** [review]
Hello, Kian. Most of your codes are commendable and follow our coding guidelines. However, there have been a few oversights in your `script.js` file.
## 1. Change the `var` keyword to `let`:

https://github.com/PUP-BSIT/exercise-14-sixth_sense/blob/7f880c27ab3346571647a87caf5a6d38ed5792bf/trinidad_kianlee/script.js#L61

As per slide 10 in our coding guidelines: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d183194fb_0_0

## 2. Use guard clause here when possible to catch early errors, such as in this case:
https://github.com/PUP-BSIT/exercise-14-sixth_sense/blob/7f880c27ab3346571647a87caf5a6d38ed5792bf/trinidad_kianlee/script.js#L62-L64

For example, you can add a guard clause if user tries to submit an empty value, or if the country does not exist. Here's a simple way of doing so:

```javascript
.then((response) => {
      if (!response.ok) {
        throw new Error('Country not found');
      }
      return response.json();
    })
``` 
This is stated in slide 10 as well: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d183194fb_0_0

## 3. The second `fetch` in your code should **NOT** be nested inside the second `then` method:
https://github.com/PUP-BSIT/exercise-14-sixth_sense/blob/7f880c27ab3346571647a87caf5a6d38ed5792bf/trinidad_kianlee/script.js#L76-L77

## Instead, you can chain them by returning another fetch. Here's a simple example of doing so:

```javascript
    .then((region) => {
      return fetch("https://restcountries.com/v3.1/region/" + region);
    })
    .then((response) => response.json())
    .then((data) => {
      let regionCountries = document.getElementById("region_countries");
      regionCountries.innerHTML = "<h2>Countries in the same region:</h2>";
      data.forEach((country) => {
        regionCountries.innerHTML += `
          <p>${country.name.common}</p>
          <img src="${country.flags.png}" alt="${country.name.common} flag">`;
      });
    })
``` 

### You can add guard clause here to improve the code.

This is also stated in the slide 14 of our coding guidelines: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g2637aafa621_0_10

## 4. Observe proper indentation here:
https://github.com/PUP-BSIT/exercise-14-sixth_sense/blob/7f880c27ab3346571647a87caf5a6d38ed5792bf/trinidad_kianlee/script.js#L79-L82

Indent lines below the `then` method.

So far, these are the immediate changes that should be made to strictly adhere to our coding guidelines. If you have any questions or concerns, feel free to raise it here right away.

**Comment by Trinidad-KianLee** [comment]
Hello @Martinez-Emmanuel, I've fixed the errors in my codes and improved it just like you have suggested. I kindly request for your review again. Thank you!

**Review by Martinez-Emmanuel — APPROVED** [review]
Your code looks much better now. There is still room for improvements but we've corrected the immediate concerns. You can review your codes again just to make sure we didn't miss anything.

With that being said, I'm now approving your codes to be merged towards the `main` branch. 

I am attaching this image below as a proof that your code works at the time of this approval:

image

**Pull request merged**
